### ISSUE TITLE
yarn 

### ISSUE THREAD

**Issue by Calumjn98** [Mojito-Fivem/mojito_crypto#10]
ive tried to install following your read me and it dosent let me place rigs im having yarn errors in console log

**Comment by Calumjn98** [comment]
[         script:yarn] Error: [yarn] warning package.json: License should be a valid SPDX license expression
[         script:yarn] 
[         script:yarn] Error: [yarn] warning mojito_crypto@1.1.0: License should be a valid SPDX license expression
[         script:yarn] 
[         script:yarn] [yarn] [1/4] Resolving packages...
[         script:yarn] 
[         script:yarn] [yarn] success Already up-to-date.
[         script:yarn] 
[         script:yarn] [yarn] Done in 0.15s.
[         script:yarn] 
[         script:yarn] SCRIPT ERROR in timer: Error: EACCES: permission denied, open '/home/zap924465/g479718/gta5-fivem-txadmin/QBCoreFramework_B88F70.base/resources/mojito_crypto/.yarn.installed'
[         script:yarn] > Object.openSync (node:fs:585)
[         script:yarn] > Object.writeFileSync (node:fs:2153)
[         script:yarn] > <unknown> (@yarn/yarn_builder.js:64)



this is my wrror in log

**Comment by Calumjn98** [comment]
okay so ive done this and my errors are gone but when clickon the rigs to open them and placeit dosen bring any placement menu up :/

**Comment by LiamDormon** [comment]
download the release or compile it manually

**Comment by Calumjn98** [comment]
ill try that thks
