### ISSUE TITLE
Item removal after use.

### ISSUE THREAD

**Issue by D40G** [Mojito-Fivem/mojito_crypto#4]
After the rigs are placed, Basic or Advanced they do not get removed from inventory and you could keep spamming them over and over and over and when you disassemble it you get more back haha

**Comment by LiamDormon** [comment]
https://github.com/Mojito-Fivem/mojito_crypto/blob/81b0d76fe0342c14baeb8cb55f37549f441985c7/server/rig/rig.service.ts#L49 they get removed after being successfully inserted into the database

**Comment by LiamDormon** [comment]
@DaShizz is this still an issue with the latest version and latest SQL ?

**Comment by D40G** [comment]
Testing now, will report after a thorough test. Thanks!

**Comment by D40G** [comment]
issue does not persist after latest
