### ISSUE TITLE
Idea?

### ISSUE THREAD

**Issue by CsGWilliams** [Mojito-Fivem/mojito_crypto#7]
Would be nice if the rigs saved position after being placed and dont disappear after you relog. 

Would also be nice if the rig was removed from your inventory after use.

These are just some suggestions!

**Comment by LiamDormon** [comment]
Both of these things are features

**Comment by CsGWilliams** [comment]
Don't know if I'm doing something wrong, but non of these things occur when I'm using it.

**Comment by LiamDormon** [comment]
Sounds like you have an issue with your database. All of the db issues were fixed in 1.0
